config/routes.rb
Rails.application.routes.draw do

  # starting with the normal routes with translated resources
  unless  Gem::Specification::find_all_by_name('route_translator').any?

    scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
      # special routes for the signup to basic newsletter
      post '/email_verification' => 'signups#email_verification'
      get '/email_confirmation' => 'signups#email_confirmation'
      # contact forms
      resources :contacts
      # Mailing list records for admin
      # for public viewing and admin editing
      resources :members do
        member do
          get   :unsubscribe_from_newsletter
          post  :validate_email
          post  :add_role
          post  :remove_role
        end
        collection do
          post :search
        end
      end
      # for user to edit and view privately
      resource :profile, only: [ :show, :edit, :update ]
      get 'profile_history' => 'profiles#history'
      resources :mailings do
        member do
          get   :sendit
          post  :duplicate
        end
      end
      post '/assign_powers' => 'powers#index'
    end

  else # special routing for localized routes via the route_translator gem

    localized do
      # special routes for the signup to basic newsletter
      post '/email_verification' => 'signups#email_verification'
      get '/email_confirmation' => 'signups#email_confirmation'
      # contact forms
      resources :contacts
      # Mailing list records for admin
      # for public viewing and admin editing
      resources :members do
        member do
          get   :unsubscribe_from_newsletter
          post  :validate_email
          post  :add_role
          post  :remove_role
        end
        collection do
          post :search
        end
      end
      # for user to edit and view privately
      resource :profile, only: [ :show, :edit, :update ]
      get 'profile_history' => 'profiles#history'
      resources :mailings do
        member do
          get   :sendit
          post  :duplicate
        end
      end
    end

  end

end

app/models/mailing.rb
class Mailing < ActiveRecord::Base

  validates_presence_of :title, :subject, :body_text, :body_html

  translates :title, :subject, :body_text, :body_html

  scope :by_recent, -> { order('created_at desc') }

  def duplicate!
    old_mailing = self
    new_mailing = old_mailing.dup
    new_mailing.title = "Copy of #{old_mailing.title}"
    new_mailing.save
    # not very pretty but it works fine. Had to do this manually otherwise the mailing
    # fields would not be duplicated over to the new course record in their respective language.
    translated_attributes = [ 'title', 'subject', 'body_text', 'body_html' ]
    I18n.available_locales.each do |loc|
      translated_attributes.each do |attr|
        new_mailing.write_attribute( attr.to_sym, self.read_attribute( attr.to_sym, locale: loc ), locale: loc)
      end
    end
    new_mailing.title = "Copy of #{new_mailing.title}"
    new_mailing.save
  end

end

app/controllers/mailings_controller.rb
class MailingsController < ApplicationController

  before_action :authenticate
  before_action -> { require_permission_to 'write_mailings'}

  def index
    @mailings = Mailing.by_recent.paginate :page => params[:page], :per_page => 25
    switch_to_admin_layout
  end

  def show
    @mailing = Mailing.find(params[:id])
    switch_to_admin_layout
  end

  def new
    @mailing = Mailing.new
    switch_to_admin_layout
  end

  def edit
    @mailing = Mailing.find(params[:id])
    switch_to_admin_layout
  end

  def create
    @mailing = Mailing.new(mailing_params)
    if @mailing.save
      redirect_to @mailing, :notice => 'Mailing was successfully created.'
    else
      render :action => "new", :warning => 'There was a problem saving the mailing.', layout: 'admin'
    end
  end

  def update
    @mailing = Mailing.find(params[:id])
    if @mailing.update_attributes(mailing_params)
      redirect_to @mailing, :notice => 'Mailing was successfully updated.'
    else
      render :action => "edit", :warning => 'There was a problem saving the mailing.', layout: 'admin'
    end
  end

  def destroy
    @mailing = Mailing.find(params[:id])
    @mailing.destroy
    redirect_to mailings_path, notice: 'You have successfully deleted one mailing.'
  end

  def sendit
    @mailing = Mailing.find(params[:id])

    if @mailing.testing?
      recipients = User.administrators
    else # prepare the actual list
      recipients = Member.validated_emails.allowed_newsletter  # production_recipients
    end

    @actual_recipient_count = 0

    recipients.each do |recipient|
      # All recipients need an auth_token to generate unsubscribe link
      unless recipient.auth_token?
        recipient.generate_token(:auth_token)
        recipient.save
      end

      # check email validity
      if valid_email?(recipient.email)
        # Actually send the email to the subscriber
        begin
          EnewsMailer.newsletter(recipient, @mailing).deliver_now
          @actual_recipient_count += 1
        rescue Exception => e
          AdminMailer.rescued_exceptions(e, "Some exception occurred while trying to send the enewsletter.").deliver_now
        end

      else # for invalid or blank emails
        Activity.create(  doer_id: recipient.id,
                          message: "was not sent the enewsletter entitled '#{@mailing.title}' because their email address appears to be blank or invalid.",
                          for_admin_only: true   )
      end
    end

    # After the mailing has been sent, finish up with the following
    if @mailing.testing?
      redirect_to mailings_path, notice: 'The test mailing is being sent. Check it carefully, fix mistakes, resend. Repeat as many times as needed.'
    else
      # TODO - notify the admins somehow -- send email upon completion
     Activity.create( doer_id: current_user.id,
                      message: " just sent the enewsletter entitled '#{@mailing.title}' to #{Member.validated_emails.allowed_newsletter.count} subscribers."  )
     redirect_to mailings_path, notice: 'The mailing is being sent to your subscribers.'
    end
  end

  def duplicate
    @mailing = Mailing.find(params[:id])
    @mailing.duplicate!
    redirect_to mailings_path
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def mailing_params
    params.require(:mailing).permit( :title, :subject, :body_text, :body_html, :admin_note, :testing )
  end

  def valid_email?(string)
    (!string.blank? && string =~ /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i) ? true : false
  end

end

app/views/mailings/_form.html.erb
<h1>Admin Section</h1>

<p>Before sending an email, you need to follow each of these steps:</p>

<ol>
	<li>Create or duplicate mailing</li>
	<li>Fill out the whole email in as many languages as your site covers.</li>
	<li>Make a test by sending the email in test mode.</li>
	<li>Check the test in your admin account.</li>
	<li>If you find any mistakes, fix them and go back to the step 3. </li>
	<li>Double check the test</li>
	<li>Triple check the test</li>
	<li>When you are sure that all is right, send out the email to the <b>actual</b> list</li>
</ol>

<%= simple_form_for @mailing, :html => { role: 'form' } do |f| %>
  <%= f.error_notification %>

	    <%= f.input :title,
									:placeholder => 'September 2015',
									:hint => 'This is just for you to recognize your different mailings at a glance',
									input_html: { size: 55 } %>
	    <%= f.input :testing, label: "testing mode? Uncheck with care!!!" %>
			<%= f.input :admin_note,
									:placeholder => 'Description to remember procedure from mailing to mailing',
									:hint => 'Just for your convenience too.',
									input_html: { cols: 55, rows: 3 } %>

										<hr />
										<h1>Actual Email</h1>


	    <%= f.input :subject,
									:placeholder => 'Very clear subject for recipients',
									:hint => "Make it good. Put yourself in your subscribers' shoes",
									input_html: { size: 55 } %>
	    <%= f.input :body_text,
									:placeholder => 'Here is the actual body text of the email',
									:hint => 'No HTML.',
									input_html: { cols: 55, rows: 15 } %>

	    <%= f.input :body_html,
									:placeholder => 'Here is the actual HTML formatted body text of the email',
									hint: "try and resist the temptation of 'styling' your pages here. Use semantic HTML markup",
									input_html: { class: 'tinymce' } %>
      <%= tinymce selector: 'input.tinymce',
                branding: false,
                # context_menu: "link image imagetools table spellchecker",
                height: 550,
                menubar: false, # hiding menu items duplicating icons
                plugins: "lists link image code fullscreen",
                toolbar: "formatselect bold italic strikethrough | bullist numlist | alignleft aligncenter alignright alignnone | link unlink image | undo redo selectall code fullscreen"
    %>
    
    <%= f.button :submit, class: 'btn btn-primary' %>

<% end %>

app/views/mailings/_header.html.erb
<h1>Mailings</h1>

<div class="panel panel-default">
  <div class="panel-body">
    Total newsletter subscribers: <strong><%= Member.validated_emails.allowed_newsletter.count %></strong>
  </div>
</div>

<%= render 'tab_admin_menu' %>

app/views/mailings/_tab_admin_menu.html.erb
<ul class="nav nav-tabs" id="admin-menu-tab">
  <%= content_tag :li, link_to('new', new_mailing_path), ({ class: 'active' } if controller.action_name.to_s == 'new' ) %>
  <%= content_tag :li, link_to('list', mailings_path), ({ class: 'active' } if controller.action_name.to_s == 'index' ) %>
  <%= content_tag :li, link_to('show', '#'), ({ class: 'active' }) if controller.action_name.to_s == 'show' %>
  <%= content_tag :li, link_to('edit', '#'), ({ class: 'active' }) if controller.action_name.to_s == 'edit' %>
</ul>

app/views/mailings/edit.html.erb
<%= render 'header' %>
<%= render 'form' %>
<%= render 'shared/admin_sidebar' %>

app/views/mailings/index.html.erb
<%= render 'header' %>

<%= will_paginate @mailings %>

<table class="table table-striped">
  <thead>
    <tr>
			<th>Title & Subject</th>
			<th>Status</th>
		  <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @mailings.each do |mailing| %>
			<tr>
				<td>
					<strong><%= link_to mailing.title, mailing %></strong><br />
					Subject: <%= mailing.subject %><br />
					<%= link_to "<span class='glyphicon glyphicon-envelope'></span> ".html_safe + 'send it now!', sendit_mailing_path(mailing), class: mailing.testing? ? 'btn btn-sm btn-success' : 'btn btn-danger' %>
				</td>
				<td><%= mailing.testing? ? "testing :-)" : "<span class='glyphicon glyphicon-alert'></span>".html_safe + " ready to publish. CAREFUL!!!!" %></td>
				<td><%= link_to "<span class='glyphicon glyphicon-pencil'></span> ".html_safe + 'edit', edit_mailing_path(mailing), :class => 'btn btn-sm btn-default' %><%= link_to "<span class='glyphicon glyphicon-trash'></span> ".html_safe + 'delete', mailing, :data => { :confirm => 'Are you sure?' }, :method => :delete, :class => 'btn btn-sm btn-danger' %><%= link_to "<span class='glyphicon glyphicon-plus'></span> ".html_safe + 'duplicate', duplicate_mailing_path(mailing), class: 'btn btn-sm btn-default', method: :post %></td>
	  	</tr>
		<% end %>

		<tr><td colspan="3"><%= link_to "<span class='glyphicon glyphicon-plus'></span>".html_safe + 'new mailing', new_mailing_path, :class => 'btn btn-default' %></td></tr>
  </tbody>
</table>

<%= will_paginate @mailings %>

<%= render 'shared/admin_sidebar' %>

app/views/mailings/new.html.erb
<%= render 'header' %>
<%= render 'form' %>
<%= render 'shared/admin_sidebar' %>

app/views/mailings/show.html.erb
<% content_for :meta_title, @mailing.title %>
<% content_for :meta_description, @mailing.title + " - " + @mailing.subject %>

<%= render 'header' %>

<h1><%= @mailing.title %></h1>

<p><strong>Subject:</strong> <%= @mailing.subject %></p>

<hr />

<%= simple_format @mailing.body_text %>

<hr>

<%= raw @mailing.body_html %>

<hr>

<p><%= link_to "<span class='glyphicon glyphicon-pencil'></span>".html_safe + ' edit this mailing', edit_mailing_path(@mailing), :class => 'btn btn-default' %><%= link_to "<span class='glyphicon glyphicon-list'></span>".html_safe + ' list all mailings', mailings_path, :class => 'btn btn-default' %></p>

<%= render 'shared/admin_sidebar' %>