config/routes.rb
Rails.application.routes.draw do

  # starting with the normal routes with translated resources
  unless  Gem::Specification::find_all_by_name('route_translator').any?

    scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
      # special routes for the signup to basic newsletter
      post '/email_verification' => 'signups#email_verification'
      get '/email_confirmation' => 'signups#email_confirmation'
      # contact forms
      resources :contacts
      # Mailing list records for admin
      # for public viewing and admin editing
      resources :members do
        member do
          get   :unsubscribe_from_newsletter
          post  :validate_email
          post  :add_role
          post  :remove_role
        end
        collection do
          post :search
        end
      end
      # for user to edit and view privately
      resource :profile, only: [ :show, :edit, :update ]
      get 'profile_history' => 'profiles#history'
      resources :mailings do
        member do
          get   :sendit
          post  :duplicate
        end
      end
      post '/assign_powers' => 'powers#index'
    end

  else # special routing for localized routes via the route_translator gem

    localized do
      # special routes for the signup to basic newsletter
      post '/email_verification' => 'signups#email_verification'
      get '/email_confirmation' => 'signups#email_confirmation'
      # contact forms
      resources :contacts
      # Mailing list records for admin
      # for public viewing and admin editing
      resources :members do
        member do
          get   :unsubscribe_from_newsletter
          post  :validate_email
          post  :add_role
          post  :remove_role
        end
        collection do
          post :search
        end
      end
      # for user to edit and view privately
      resource :profile, only: [ :show, :edit, :update ]
      get 'profile_history' => 'profiles#history'
      resources :mailings do
        member do
          get   :sendit
          post  :duplicate
        end
      end
    end

  end

end

app/models/profile.rb
class Profile < User

  mount_uploader :portrait, PortraitUploader
  # crop_uploaded :portrait

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  after_update :crop_portrait

  def crop_portrait
    portrait.recreate_versions! if crop_x.present?
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  before_action :authenticate

  before_action :set_profile

  def show
  end

  def edit
  end

  def update
    if @profile.update_attributes(profile_params)
      if params[:profile][:portrait].present?
        render :crop  ## Render the view for cropping
      else
        Activity.create doer_id: current_user.id, message: "performed a profile edit. See #{view_context.link_to 'public profile', member_path(@profile)}."
        redirect_to profile_path, notice: "<strong><span class=\"glyphicon glyphicon-ok-sign\"></span>&nbsp;&nbsp;Success!</strong> Your profile was updated."
      end
    else
      render action: "edit", warning: "<strong>Attention!</strong> A problem occurred while trying to update your profile. Plese try again."
    end
  end

  def history
    @activities = doer.activities.by_recent
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_profile
    @profile = Profile.find(current_user)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def profile_params
    params.require(:profile).permit :email, :first_name, :last_name, :other_name, :teacher_status, :portrait, :website_url, :facebook_url, :twitter_handle, :google_plus_url, :allow_newsletter, :allow_daily_digests, :crop_x, :crop_y, :crop_w, :crop_h
  end

end

app/views/profiles/_admin_context_menu.html.erb
<% if administrator? %>

  <% content_for :admin_context_menu do %>

    <h2><%= t('admin_section') %></h2>
    <ul class="list-group">
      <li class="list-group-item"><%= link_to t('admin_panel'), members_path %></li>
      <%= content_tag :li, link_to( "#{t('activerecord.models.comments').capitalize} <span class='badge'>#{Comment.pending.count}</span>".html_safe, pending_comments_path ), class: 'list-group-item' if Comment.pending.count > 0 %>
      <% if controller.action_name == 'show' %>
      <% end %>
    </ul>

  <% end -%>

<% end -%>

app/views/profiles/_custom_private_profile_attributes.html.erb
<% # place partial of same name in /app/views/profiles to add fields %>

app/views/profiles/_custom_public_profile_attributes.html.erb
<% # place partial of same name in /app/views/profiles to add fields %>

app/views/profiles/_tab_menu.html.erb
<ul class="nav nav-tabs" id="tab-menu">
  <%= content_tag :li, link_to('<span class="glyphicon glyphicon-user"></span>&nbsp;profile'.html_safe, profile_path), ({ class: 'active' } if controller.action_name.to_s == 'show' ) %>
  <%= content_tag :li, link_to("<span class=\"glyphicon glyphicon-pencil\"></span>&nbsp;#{t('edit')}".html_safe, edit_profile_path), ({ class: 'active' } if controller.action_name.to_s == 'edit' ) %>
  <%= content_tag :li, link_to('history', profile_history_path), ({ class: 'active' } if controller.action_name.to_s == 'history' ) %>
</ul>

app/views/profiles/crop.html.erb
<% content_for :meta_title, "Crop your profile portrait" %>
<% content_for :meta_description, "Exact cropping of the profile portrait picture." %>

<h1>Crop Portrait Photo</h1>

<%= form_for @profile, url: profile_path, method: :patch do |f| %>
  <% %w[x y w h].each do |attribute| %>
    <%= f.hidden_field "crop_#{attribute}" %>
  <% end %>
  <%= f.submit "Crop" %>
<% end %>
&nbsp;&nbsp;&nbsp;
<div style="width:100px; height:100px; overflow:hidden; display: inline-block; margin-bottom: -8px;">
  <%= image_tag @profile.portrait.url(:xl), id: "preview" %>
</div>

<br /><br />

<%= image_tag @profile.portrait_url(:xl), id: "cropbox" %>

app/views/profiles/edit.html.erb
<% content_for :meta_title, 'Editing My Profile' %>
<% content_for :meta_description, "This is where the site's user can edit his or her profile information" %>

<%= render 'tab_menu' %>

<%= simple_form_for @profile, url: profile_path do |f| %>
  <%= f.error_notification %>

    <h1>Private Information</h1>
    <p>Email: <strong><%= @profile.email %></strong>. Unfortunately, you cannot yet change your email address. This feature is coming soon.</p>
    <%= f.input :allow_newsletter, label: "Allow rare newsletter?&nbsp;&nbsp;".html_safe, hint: 'never more than once a month' %>
    <%= f.input :allow_daily_digests, label: "Allow daily activity digests?&nbsp;&nbsp;".html_safe, hint: "replies to your comments, etc." %>

    <h1>Public Information</h1>
    <%= f.input :first_name, label: t('activerecord.attributes.users.first_name') %>
    <%= f.input :last_name, label: t('activerecord.attributes.users.last_name') %>
    <%= f.input :other_name, label: render( 'shared/other_name_label') %>
    <%= f.input :portrait %>
    <%= f.input :website_url, hint: "DO include http:// or https://" %>
    <%= f.input :facebook_url, hint: "DO include http:// or https://" %>
    <%= f.input :twitter_handle, hint: "Only the handle. The part after @" %>
    <%= f.input :google_plus_url, label: "Google+ url", hint: "DO include http:// or https://" %>

    <%= f.button :submit, :class => 'btn btn-primary' %>
<% end %>

<%= render'admin_context_menu' %>
<%# partial in tkh_menus gem or has to be added in host app %>
<%= render './shared/menus' %>

app/views/profiles/history.html.erb
<% content_for :meta_title, 'My Profile History' %>
<% content_for :meta_description, "List of a user's historical activities on the site." %>

<%= render 'tab_menu' %>

<div id="profile-title">
  <% if @profile.other_name.present? %>
    <h1>
      <%= @profile.other_name %><br />
      <span class="secondary-name"><%= @profile.name %></span>
    </h1>
  <% else %>
    <h1><%= @profile.name %></h1>
  <% end %>
</div>

<br />

<table class='table table-striped'>
  <thead>
    <tr>
      <th>When?</th>
      <th>What happened?</th>
    </tr>
  </thead>

  <tbody>
    <% if @activities.any? %>
      <% @activities.each do |activity| %>
        <tr>
          <td><%= human_date_and_time(activity.created_at) %></td>
            <td><%= "You #{activity.message}".html_safe %></td>
        </tr>
      <% end %>
    <% else # no activities %>
      <tr><td>You don't have any activities yet.</td></tr>
    <% end %>
  </tbody>
</table>

<%= render 'admin_context_menu' %>
<%# partial in tkh_menus gem or has to be added in host app %>
<%= render './shared/menus' %>

app/views/profiles/show.html.erb
<% content_for :meta_title, 'My Profile' %>
<% content_for :meta_description, "My profile administration section for the logged in user" %>

<%= render 'tab_menu' %>

<div id="profile-title">
  <% if @profile.other_name.present? %>
    <h1>
      <%= @profile.other_name %><br />
      <span class="secondary-name"><%= @profile.name %></span>
    </h1>
  <% else %>
    <h1><%= @profile.name %></h1>
  <% end %>
  <% if @profile.portrait.present? %>
    <p id="profile-portrait"><%= image_tag @profile.portrait_url(:small), title: @profile.name, alt: @profile.name, id: 'profile-portrait' %></p>
  <% end %>
</div>

<table id="profile-attributes">
  <tbody>

    <tr><td class="section" colspan="2"><span class="label label-danger">private information</span></td></tr>
    <tr><td class="key"><span class="glyphicon glyphicon-envelope"></span> email address</td><td class="value"><%= @profile.email %></td></tr>
    <tr><td class="key">get rare newsletter</td>
      <td class="value"><%= @profile.allow_newsletter == true ? "<span class=\"glyphicon glyphicon-ok\"".html_safe : "<span class=\"glyphicon glyphicon-remove\"".html_safe %></td>
    </tr>
    <tr>
      <td class="key">get your daily activity digests</td>
      <td class="value"><%= @profile.allow_daily_digests == true ?  "<span class=\"glyphicon glyphicon-ok\"".html_safe : "<span class=\"glyphicon glyphicon-remove\"".html_safe %></td>
    </tr>
    <%= render 'custom_private_profile_attributes' %>

    <tr><td class="section" colspan="2"><span class="label label-success">public information</span></td></tr>
    <tr><td class="key">first name</td><td class="value"><%= @profile.first_name %></td></tr>
    <tr><td class="key">last name</td><td class="value"><%= @profile.last_name %></td></tr>
    <tr><td class="key"><%= render 'shared/other_name_label' %></td><td class="value"><%= @profile.other_name %></td></tr>
    <tr><td class="key">website</td><td class="value"><%= link_to "#{URI(@profile.website_url).host}#{URI(@profile.website_url).path}#{URI(@profile.website_url).query}#{URI(@profile.website_url).fragment}", @profile.website_url, rel: 'nofollow' unless @profile.website_url.nil? %></td></tr>
    <tr><td class="key">facebook</td><td class="value"><%= link_to "#{URI(@profile.facebook_url).host}#{URI(@profile.facebook_url).path}#{URI(@profile.facebook_url).query}#{URI(@profile.facebook_url).fragment}", @profile.facebook_url, rel: 'nofollow' unless @profile.facebook_url.nil? %></td></tr>
    <tr><td class="key">twitter</td><td class="value"><%= link_to @profile.twitter_handle, "https://twitter.com/#{@profile.twitter_handle}", rel: 'nofollow' unless @profile.twitter_handle.nil? %></td></tr>
    <tr><td class="key">google+</td><td class="value"><%= link_to "#{URI(@profile.google_plus_url).host}#{URI(@profile.google_plus_url).path}#{URI(@profile.google_plus_url).query}#{URI(@profile.google_plus_url).fragment}", @profile.google_plus_url, rel: 'nofollow' unless @profile.google_plus_url.nil? %></td></tr>
    <%= render 'custom_public_profile_attributes', member: @profile %>

  </tbody>
</table>

<p class="text-center"><%= link_to "<span class=\"glyphicon glyphicon-pencil\"></span> change your info".html_safe, edit_profile_path, class: 'btn btn-sm btn-default' %></p>

<%= render'admin_context_menu' %>
<%# partial in tkh_menus gem or has to be added in host app %>
<%= render './shared/menus' %>