config/routes.rb
Rails.application.routes.draw do

  # starting with the normal routes with translated resources
  unless  Gem::Specification::find_all_by_name('route_translator').any?

    scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
      # special routes for the signup to basic newsletter
      post '/email_verification' => 'signups#email_verification'
      get '/email_confirmation' => 'signups#email_confirmation'
      # contact forms
      resources :contacts
      # Mailing list records for admin
      # for public viewing and admin editing
      resources :members do
        member do
          get   :unsubscribe_from_newsletter
          post  :validate_email
          post  :add_role
          post  :remove_role
        end
        collection do
          post :search
        end
      end
      # for user to edit and view privately
      resource :profile, only: [ :show, :edit, :update ]
      get 'profile_history' => 'profiles#history'
      resources :mailings do
        member do
          get   :sendit
          post  :duplicate
        end
      end
      post '/assign_powers' => 'powers#index'
    end

  else # special routing for localized routes via the route_translator gem

    localized do
      # special routes for the signup to basic newsletter
      post '/email_verification' => 'signups#email_verification'
      get '/email_confirmation' => 'signups#email_confirmation'
      # contact forms
      resources :contacts
      # Mailing list records for admin
      # for public viewing and admin editing
      resources :members do
        member do
          get   :unsubscribe_from_newsletter
          post  :validate_email
          post  :add_role
          post  :remove_role
        end
        collection do
          post :search
        end
      end
      # for user to edit and view privately
      resource :profile, only: [ :show, :edit, :update ]
      get 'profile_history' => 'profiles#history'
      resources :mailings do
        member do
          get   :sendit
          post  :duplicate
        end
      end
    end

  end

end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates_presence_of :sender_name
  validates_presence_of :sender_email
  # validates :sender_email, :presence => true, :format => { :with => /\A([\A@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :on => :create }
  validates_presence_of :body

  # tkh_mailing_list sends daily digest with yesterday's contacts
  scope :yesterdays, lambda { where('created_at >= ? AND created_at <= ?', 1.day.ago.beginning_of_day, 1.day.ago.end_of_day ) }
  scope :chronologically, -> { order('created_at') }
  scope :by_recent, -> { order('created_at desc') }

  attr_accessor :website

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :authenticate,                             except: [ :create ]
  before_action -> { require_permission_to 'write_contacts'}, except: [ :create ]

  def index
    @contacts = Contact.by_recent.paginate(:page => params[:page], :per_page => 35)
    switch_to_admin_layout
  end

  def show
    @contact = Contact.find(params[:id])
    switch_to_admin_layout
  end

  def create
    @contact = Contact.new(contact_params)
    # the website form field is invisible to human visitors and works as
    # a honeypot to spam robots
    honeypotted = @contact.website.present?
    saved = @contact.save unless honeypotted
    # disabling this and replacing it with a daily digest
    # this is to mitigate the pain associated with contact spams
    # sent_email = send_message_to_admin(@contact)
    # if saved && sent_email == 'success'
    #   redirect_to root_path, notice: t("contacts.create.notice")
    # elsif saved && sent_email == 'exception'
    #   flash[:error] = t("contacts.create.warning")
    #   redirect_to :back
    # elsif saved && sent_email == 'invalid'
    #   flash[:error] =  "#{t("contacts.create.warning")} #{t('contacts.create.invalid_email')}"
    #   redirect_to :back
    # else
    #   flash[:error] = t('contacts.create.did_not_reach')
    #   redirect_to :back
    # end

    if saved || honeypotted
      redirect_to root_path, notice: t("contacts.create.notice")
    else
      redirect_to :back, alert: t('contacts.create.did_not_reach')
    end
  end

  def valid_email?(string)
    (!string.blank? && string =~ /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i) ? true : false
  end
  # helper_method :valid_email?

  private

  #  disabled to be replaced by daily digest to admins
  # def send_message_to_admin(contact)
  #   # check email validity
  #   if valid_email?(contact.sender_email)
  #     # Actually send the email to the student
  #     begin
  #       ContactMailer.message_from_contact_form(contact).deliver
  #       return 'success'
  #     rescue Exception => e
  #       AdminMailer.rescued_exceptions(e, "Some exception occurred while trying to send to site admin a message from contact form").deliver
  #       @exception = e
  #       return 'exception'
  #     end
  #   else # for invalid or blank emails
  #     return 'invalid'
  #   end
  # end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:sender_name, :sender_email, :body, :website)
  end


end

app/views/contacts/_form.html.erb
<%= simple_form_for Contact.new do |f| %>
	<%= f.error_notification %>

		<%= f.input :sender_name, label: t('activerecord.attributes.contacts.sender_name') %>
		<%= f.input :sender_email, label: t('activerecord.attributes.contacts.sender_email') %>
    <%= f.input :website, label: 'website' %>
		<%= f.input :body, label: t('activerecord.attributes.contacts.body'), :input_html => { :rows => 10 } %>

    <%= f.button :submit, t('contacts.send_message'), :class => 'btn btn-primary' %>
<% end %>

app/views/contacts/_tab_admin_menu.html.erb
<ul class="nav nav-tabs" id="admin-menu-tab">
	<%= content_tag :li, link_to(t('list'), contacts_path), ({ class: 'active' } if controller.action_name.to_s == 'index' ) %>
	<%= content_tag :li, link_to(t('view'), contacts_path), ({ class: 'active' }) if controller.action_name.to_s == 'show' %>
</ul>

app/views/contacts/index.html.erb
<h1><%= t 'activerecord.models.contacts' %></h1>
<%= render 'tab_admin_menu' %>

<table class='table table-striped'>
	<thead>
  <tr>
	    <th><%= t 'activerecord.attributes.contacts.sender_name' %></th>
	    <th><%= t 'activerecord.attributes.contacts.sender_email' %></th>
			<th><%= t 'activerecord.attributes.contacts.body' %></th>
			<th><%= t 'contacts.sent' %></th>
	    <th><%= t('actions') %></th>
	  </tr>
	</thead>

	<tbody>
		<% @contacts.each do |contact| %>
		  <tr>
		    <td><%= contact.sender_name %></td>
				<td><%= link_to contact.sender_email, "mailto:#{contact.sender_email}" %></td>
		    <td><%= truncate contact.body, length: 85, separator: ' ...' %></td>
				<td><%= l contact.created_at, :format => :tkh_default %></td>
		    <td><%= link_to "<span class=\"glyphicon glyphicon-eye-open\"></span>&nbsp;#{t('view')}".html_safe, contact, class: 'btn btn-xs btn-default' %></td>
		  </tr>
		<% end %>
	</tbody>
</table>

<%= will_paginate @contacts %>

<%= render 'shared/admin_sidebar' %>

app/views/contacts/show.html.erb
<h1><%= t('activerecord.models.contacts') %></h1>

<%= render 'tab_admin_menu' %>

<h2><%= "#{t('contacts.sent')}#{t('colon')} #{ l(@contact.created_at, :format => :tkh_default) }" %></h2>

<p>
	<%= "#{t('activerecord.attributes.contacts.sender_name').capitalize}#{t('colon')} #{@contact.sender_name}" %><br />
	<%= "#{t('activerecord.attributes.contacts.sender_email')}#{t('colon')} #{link_to(@contact.sender_email, "mailto:#{@contact.sender_email}")}".capitalize.html_safe %>
</p>
<h3><%= t('activerecord.attributes.contacts.body').capitalize %></h3>
<p><%= sanitize @contact.body.gsub(/\r\n?/, "<br>"), :tags => %w(br), :attributes => %w() %></p>

<hr>

<p><%= link_to t('list'), contacts_path, class: 'btn' %></p>

<%= render 'shared/admin_sidebar' %>