config/routes.rb
Rails.application.routes.draw do

  # starting with the normal routes with translated resources
  unless  Gem::Specification::find_all_by_name('route_translator').any?

    scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
      # special routes for the signup to basic newsletter
      post '/email_verification' => 'signups#email_verification'
      get '/email_confirmation' => 'signups#email_confirmation'
      # contact forms
      resources :contacts
      # Mailing list records for admin
      # for public viewing and admin editing
      resources :members do
        member do
          get   :unsubscribe_from_newsletter
          post  :validate_email
          post  :add_role
          post  :remove_role
        end
        collection do
          post :search
        end
      end
      # for user to edit and view privately
      resource :profile, only: [ :show, :edit, :update ]
      get 'profile_history' => 'profiles#history'
      resources :mailings do
        member do
          get   :sendit
          post  :duplicate
        end
      end
      post '/assign_powers' => 'powers#index'
    end

  else # special routing for localized routes via the route_translator gem

    localized do
      # special routes for the signup to basic newsletter
      post '/email_verification' => 'signups#email_verification'
      get '/email_confirmation' => 'signups#email_confirmation'
      # contact forms
      resources :contacts
      # Mailing list records for admin
      # for public viewing and admin editing
      resources :members do
        member do
          get   :unsubscribe_from_newsletter
          post  :validate_email
          post  :add_role
          post  :remove_role
        end
        collection do
          post :search
        end
      end
      # for user to edit and view privately
      resource :profile, only: [ :show, :edit, :update ]
      get 'profile_history' => 'profiles#history'
      resources :mailings do
        member do
          get   :sendit
          post  :duplicate
        end
      end
    end

  end

end

app/models/member.rb
class Member < User

  scope :validated_emails, -> { where('email_validated = ?', true) }
  scope :allowed_newsletter, -> { where('allow_newsletter = ?', true) }

  def unsubscribe_from_newsletter!
    # for some reason the self bit is necessary. I thought it would not be.
    self.allow_newsletter = false
    self.save
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  before_action :authenticate,  except: [ :show, :unsubscribe_from_newsletter ]
  before_action -> { require_permission_to 'write_members'},
                                except: [ :show, :unsubscribe_from_newsletter ]
  before_action -> { require_permission_to 'write_roles'},
                                only: [ :add_role, :remove_role ]

  before_action :set_member, only: [ :show, :edit, :update, :destroy, :validate_email, :add_role, :remove_role ]

  def index
    @members = Member.by_recent.paginate(:page => params[:page], :per_page => 30)
    switch_to_admin_layout
  end

  def show
  end

  def new
    @member = Member.new
    switch_to_admin_layout
  end

  def edit
    switch_to_admin_layout
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      redirect_to members_path, notice: t('members.create.notice')
    else
      render action: "new", warning: t('members.create.warning'), layout: 'admin'
    end
  end

  def update
    if @member.update_attributes(member_params)
      redirect_to members_path, notice: t('members.update.notice')
    else
      render action: "edit", warning: t('members.update.warning'), layout: 'admin'
    end
  end

  def destroy
    if @member.destroy
      redirect_to members_path, notice: t('members.destroy.notice')
    else
      redirect_to members_path, warning: t('members.destroy.warning')
    end
  end

  def search
    @members = Member.where("LOWER(first_name) LIKE ? OR LOWER(last_name) LIKE ? OR LOWER(other_name) LIKE ? OR LOWER(email) LIKE ?", "%#{params[:query].downcase}%", "%#{params[:query].downcase}%", "%#{params[:query].downcase}%", "%#{params[:query].downcase}%").by_recent.limit(25)
  end

  def unsubscribe_from_newsletter
    @member = Member.find_by_auth_token(params[:id])
    @member.unsubscribe_from_newsletter!
    if Activity.create(   doer_id: @member.id,
                          message: "just <strong>unsubscribed</strong> from the <strong>enewsletter</strong>."   )
      redirect_to root_path, notice: "You have been successfully unsubscribed from our newsletter. Bye bye :-)"
    else
      redirect_to root_path, warning: "ATTENTION! There was a problem unsubscribing you from the newsletter. We do want to do our best to help you though. Please send an email to #{Setting.first.contact_email}"
    end
  end

  def validate_email
    @member.email_validated = true
    @member.save
    redirect_to members_path, notice: "Successfully validated the #{@member.email} email address."
  end

  def add_role
    role = Role.find(params[:role_id])
    @member.roles << role
    redirect_to members_path, notice: "The '#{role.name}' role has been added to #{@member.name}"
  end

  def remove_role
    role = Role.find(params[:role_id])
    @member.roles.delete role
    redirect_to members_path, notice: "The '#{role.name}' role has been removed from #{@member.name}"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_member
    @member = Member.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def member_params
    params.require(:member).permit :email, :first_name, :last_name, :other_name, :teacher_status, :portrait, :website_url, :facebook_url, :twitter_handle, :google_plus_url, :allow_newsletter, :allow_daily_digests
  end

end

app/helpers/members_helper.rb
module  MembersHelper

  def abridged_url(str)
    if str.present?
      uri = URI(str)
      "#{uri.host}#{uri.path}#{uri.query}#{uri.fragment}"
    else # string is blank
      ''
    end
  end
end

app/views/members/_admin_context_menu.html.erb
<% if administrator? %>

  <% content_for :admin_context_menu do %>

    <h2><%= t('admin_section') %></h2>
    <ul class="list-group">
      <li class="list-group-item"><%= link_to t('admin_panel'), members_path %></li>
      <%= content_tag :li, link_to( "#{t('activerecord.models.comments').capitalize} <span class='badge'>#{Comment.pending.count}</span>".html_safe, pending_comments_path ), class: 'list-group-item' if Comment.pending.count > 0 %>
      <% if controller.action_name == 'show' %>
        <li class="list-group-item"><%= link_to 'Modify this member record', edit_member_path(member) %></li>
      <% end %>
    </ul>

  <% end -%>

<% end -%>

app/views/members/_assign_roles_form.html.erb
<h2>Roles</h2>

<%= form_tag '/assign_powers' do |f| %>

  <%= hidden_field_tag :user_id, @member.id %>

  <ul class="list-group">
    <% Role.alphabetically.each do |role| %>
      <li class="list-group-item">
        <% if @member.has_role? role.name %>
          <span class='glyphicon glyphicon-ok'></span>  <strong><%= role.name %></strong>
          <%= link_to "<span class='glyphicon glyphicon-trash'></span> remove".html_safe, remove_role_member_path(role_id: role.id), method: :post, class: 'btn btn-xs btn-danger' %>
          <%= content_tag :span, role.description, class: 'role-explanation' %>
        <% else %>
          <%= role.name %>
          <%= link_to "<span class='glyphicon glyphicon-plus'></span> add".html_safe, add_role_member_path(role_id: role.id), method: :post, class: 'btn btn-xs btn-success' %>
          <%= content_tag :span, role.description, class: 'role-explanation' %>
        <% end %>
       </li>
    <% end %>
  </ul>

<% end %>

app/views/members/_form.html.erb
<%= simple_form_for @member, :html => { multipart: true } do |f| %>
  <%= f.error_notification %>

    <h2>Private Fields</h2>
    <%= f.input :email, label: t('activerecord.attributes.users.email'), hint: 'change with caution!!!! the email is used to login.' %>
    <%= f.input :allow_newsletter %>
    <%= f.input :allow_daily_digests %>

    <h2>Public Fields</h2>
    <%= f.input :first_name, label: t('activerecord.attributes.users.first_name') %>
    <%= f.input :last_name, label: t('activerecord.attributes.users.last_name') %>
    <%= f.input :other_name, label: t('activerecord.attributes.users.other_name'), hint: 'nickname, spiritual name, etc.' %>
    <%= f.input :website_url %>
    <%= f.input :facebook_url %>
    <%= f.input :twitter_handle %>
    <%= f.input :google_plus_url, label: "Google+ url" %>

    <%= f.button :submit, :class => 'btn btn-primary' %>
<% end %>

app/views/members/_header.html.erb
<h1><%= number_with_delimiter Member.count %> Members</h1>

<%= render 'tab_admin_menu' %>

app/views/members/_search_results.js.erb
<% @members.each do |member| %>
  <tr>
    <td><%= link_to member.name, member, title: 'view' %></td>
    <td><%= member.email %></td>
    <td>
      <% member.role_names.each do |name| %>
        <%="<span class='label label-info'>#{name}</span>".html_safe %>
      <% end %>
    </td>
    <td><%= link_to "<span class='glyphicon glyphicon-pencil'></span> ".html_safe + t('edit'), edit_member_path(member), :class => 'btn btn-xs btn-default' %><%= link_to "<span class='glyphicon glyphicon-trash'></span> ".html_safe + t('delete'), member, method: :delete, data: { confirm: t('are_you_sure') }, class: 'btn btn-xs btn-danger' %></td>
  </tr>
<% end %>

app/views/members/_tab_admin_menu.html.erb
<ul class="nav nav-tabs" id="admin-menu-tab">
  <%= content_tag :li, link_to(t('new'), new_member_path), ({ class: 'active' } if controller.action_name.to_s == 'new' ) %>
  <%= content_tag :li, link_to(t('list'), members_path), ({ class: 'active' } if controller.action_name.to_s == 'index' ) %>
  <%= content_tag :li, link_to(t('edit'), '#'), ({ class: 'active' }) if controller.action_name.to_s == 'edit' %>
</ul>

app/views/members/edit.html.erb
<%= render 'header' %>

<%= render 'form' %>
<%= render 'assign_roles_form' if current_user.is_allowed_to?('write_roles') %>

<%= render 'shared/admin_sidebar' %>

app/views/members/index.html.erb
<%= render 'header' %>

<%= form_tag search_members_path, remote: true, id: "search-form", class: 'text-center' do %>
  <%= text_field_tag :query,
                        nil,
                        autofocus: true,
                        placeholder: "eg. john, or smith, or smit",
                        class: 'search-field',
                        size: 55 %><br /><br />
  <%= button_tag type: 'submit', class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-search"></span>&nbsp;<%= 'search in names and email' %>
  <% end %>
<% end %>

<%= will_paginate @members, inner_window: 2 %>

<table id="member-list" class='table table-striped'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Roles</th>
      <th><%= t('actions') %></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.name, member, title: 'view' %></td>
        <td>
          <%= member.email %>
          <% unless member.email_validated? %>
            <span class="glyphicon glyphicon-remove"></span>
            <%= link_to "<span class='glyphicon glyphicon-ok'></span> validate!!! <span class='glyphicon glyphicon-warning-sign'></span>".html_safe, validate_email_member_path(member), method: 'post', class: 'btn btn-xs btn-default' %>
          <% end %>
        </td>
        <td>
          <% member.role_names.each do |name| %>
            <%="<span class='label label-info'>#{name}</span>".html_safe %>
          <% end %>
          </td>
        <td><%= link_to "<span class='glyphicon glyphicon-pencil'></span> ".html_safe + t('edit'), edit_member_path(member), :class => 'btn btn-xs btn-default' %><%= link_to "<span class='glyphicon glyphicon-trash'></span> ".html_safe + t('delete'), member, method: :delete, data: { confirm: t('are_you_sure') }, class: 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @members, inner_window: 2 %>

<p><%= link_to "<span class='glyphicon glyphicon-plus'></span> Add a New Member".html_safe, new_member_path, class: 'btn btn-default' %></p>

<%= render 'shared/admin_sidebar' %>

app/views/members/new.html.erb
<%= render 'header' %>

<%= render 'form' %>

<%= render 'shared/admin_sidebar' %>

app/views/members/search.js.erb
$('table#member-list tbody').html("<%= escape_javascript(render(partial: 'search_results', members: @members)) %>").hide().show("highlight", { color: "#772953" }, 1500);

app/views/members/show.html.erb
<% content_for :meta_title, @member.name %>
<% content_for :meta_description, "Public profile for #{@member.name}" %>

<div id="profile-title">
  <% if @member.other_name.present? %>
    <h1>
      <%= @member.other_name %><br />
      <span class="secondary-name"><%= @member.name %></span>
    </h1>
  <% else %>
    <h1><%= @member.name %></h1>
  <% end %>
  <% if Profile.find(@member.id).portrait.present? %>
    <p id="profile-portrait"><%= image_tag Profile.find(@member.id).portrait_url(:small), title: @member.name, alt: @member.name, id: 'profile-portrait' %></p>
  <% end %>
</div>

<table id="profile-attributes">
  <tbody>
    <tr><td class="key">website</td><td class="value"><%= link_to abridged_url(@member.website_url), @member.website_url, rel: 'nofollow' %></td></tr>
    <tr><td class="key">facebook</td><td class="value"><%= link_to abridged_url(@member.facebook_url), @member.facebook_url, rel: 'nofollow' %></td></tr>
    <tr><td class="key">twitter</td><td class="value"><%= @member.twitter_handle.present? ? link_to( @member.twitter_handle, "https://twitter.com/#{@member.twitter_handle}", rel: 'nofollow' ) : '' %></td></tr>
    <tr><td class="key">google+</td><td class="value"><%= link_to abridged_url(@member.google_plus_url), @member.google_plus_url, rel: 'nofollow' %></td></tr>
    <%= render 'profiles/custom_public_profile_attributes', member: @member %>
  </tbody>
</table>

<%= render 'admin_context_menu', member: @member %>
<%# partial in tkh_menus gem or has to be added in host app %>
<%= render './shared/menus' %>